DROP DATABASE IF EXISTS `learningProcess`;
CREATE DATABASE IF NOT EXISTS `learningProcess`;
USE `learningProcess`;
DROP TABLE IF EXISTS  `process`;

CREATE TABLE IF NOT EXISTS `process`(
    `id` INT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
    `date` DATE NOT NULL COMMENT '日期',
    `time` TIMESTAMP NOT NULL COMMENT '时间',
    `class` VARCHAR(100) NOT NULL COMMENT '课程的名称',
    `process` VARCHAR(100) NOT NULL COMMENT '课程的进度',
    PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
